# Generated by Django 4.2.23 on 2025-08-06 11:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('task_type', models.CharField(choices=[('project', 'Project'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('full_time', 'Full Time'), ('part_time', 'Part Time')], default='project', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('currently_working', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('technologies_used', models.TextField(help_text='Technologies/tools used (comma separated)')),
                ('achievements', models.TextField(blank=True)),
                ('key_responsibilities', models.TextField(blank=True)),
                ('project_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='InterviewExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('interview_date', models.DateField()),
                ('status', models.CharField(choices=[('selected', 'Selected'), ('rejected', 'Rejected'), ('pending', 'Pending'), ('in_progress', 'In Progress')], default='pending', max_length=20)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('duration', models.CharField(blank=True, max_length=50)),
                ('rounds', models.IntegerField(default=1)),
                ('description', models.TextField()),
                ('technical_questions', models.TextField(blank=True)),
                ('hr_questions', models.TextField(blank=True)),
                ('tips', models.TextField(blank=True)),
                ('rating', models.IntegerField(default=5, help_text='Rate your experience from 1 to 5')),
                ('salary_offered', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_experiences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
